[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
[project]
dependencies = [
  'scikit-learn >= 1.0.0',
  'numpy >= 1.20',
  'pandas > 1.2.0',
  'ray >= 1.9.0',
  'lightgbm >= 3.3.1'
]
build-backend = "setuptools.build_meta"